<a href="https://colab.research.google.com/github/student-monika/Marvel_tasks/blob/main/Marvel_L2_Task_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Define a small array
small_array = np.array([[1, 2], [3, 4]])

# Repeat the small array across each dimension
repeated_array = np.tile(small_array, (2, 3))

print("Repeated Array:\n", repeated_array)

# Task 2: Generate an array with element indexes such that the array elements appear in ascending order

# Define an array
arr = np.array([50, 20, 30, 10, 40])

# Get an array of indexes that would sort the array
sorted_indices = np.argsort(arr)

print("\nOriginal Array:", arr)
print("Sorted Indices:", sorted_indices)


Repeated Array:
 [[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]

Original Array: [50 20 30 10 40]
Sorted Indices: [3 1 2 4 0]
