<a href="https://colab.research.google.com/github/student-monika/Marvel_tasks/blob/main/Marvel_L2_Task_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Regression metrics
-> California housing dataset

In [ ]:
# Import necessary libraries
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Step 1: Load the California Housing dataset
data = fetch_california_housing()
X, y = data.data, data.target

# Step 2: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 3: Fit a Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Step 4: Make predictions on the test set
y_pred = model.predict(X_test)

# Step 5: Calculate Regression Metrics
mae = mean_absolute_error(y_test, y_pred)  # Mean Absolute Error
mse = mean_squared_error(y_test, y_pred)  # Mean Squared Error
rmse = np.sqrt(mse)  # Root Mean Squared Error
r2 = r2_score(y_test, y_pred)  # R-squared

# Step 6: Print the regression metrics
print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("R-squared (R²):", r2)


Mean Absolute Error (MAE): 0.5272474538306174
Mean Squared Error (MSE): 0.5305677824766757
Root Mean Squared Error (RMSE): 0.7284008391515455
R-squared (R²): 0.595770232606166


Classification metrics
-> Wine data set

In [ ]:
# Import necessary libraries
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Step 1: Load the Wine dataset
wine_data = load_wine()
X, y = wine_data.data, wine_data.target

# Step 2: Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 3: Split the scaled data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

# Step 4: Fit a Logistic Regression model with increased max_iter and a different solver
classifier = LogisticRegression(max_iter=500, solver='liblinear')
classifier.fit(X_train, y_train)

# Step 5: Make predictions on the test set
y_pred = classifier.predict(X_test)

# Step 6: Calculate Classification Metrics
accuracy = accuracy_score(y_test, y_pred)  # Accuracy
precision = precision_score(y_test, y_pred, average='weighted')  # Precision
recall = recall_score(y_test, y_pred, average='weighted')  # Recall
f1 = f1_score(y_test, y_pred, average='weighted')  # F1 Score
conf_matrix = confusion_matrix(y_test, y_pred)  # Confusion Matrix

# Step 7: Print classification metrics
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:\n", conf_matrix)


Accuracy: 0.9814814814814815
Precision: 0.9824074074074074
Recall: 0.9814814814814815
F1 Score: 0.9814930627938757
Confusion Matrix:
 [[19  0  0]
 [ 1 20  0]
 [ 0  0 14]]
